// Postman collection -> tests/api/<collection>.spec.ts using Playwright's `request` fixture. Pure.
import type { TestSuite } from '../model.js';
import { q } from '../locators.js';
import { indent, statusOf, type ConversionStatus } from './steps.js';
import type { GenResult } from './pages.js';

export interface ApiResult extends GenResult { tests: { name: string; status: ConversionStatus; total: number; todos: number }[]; noAssertion: string[] }

export function apiSpecFileName(suite: TestSuite): string {
  const base = suite.source.replace(/^.*\//, '').replace(/\.postman_collection\.json$|\.json$/i, '').replace(/[^A-Za-z0-9._-]+/g, '-');
  return `tests/api/${base}.spec.ts`;
}

const IGNORABLE = /^\s*(?:pm\.test\(.*(?:function\s*\([^)]*\)|=>)\s*\{?|\}\s*\)?;?|pm\.response\.to\.have\.status\(\d+\);?|pm\.expect\(pm\.response\.code\)\.to\.(?:eql|equal)\(\d+\);?|pm\.test\(.*to\.have\.status\(\d+\)\);?)\s*$/;

export function genApiSpec(suite: TestSuite): ApiResult {
  const todos: GenResult['todos'] = [];
  const tests: ApiResult['tests'] = [];
  const noAssertion: string[] = [];
  const vars = suite.variables ?? {};
  const out: string[] = [];
  out.push(`// Generated by sdet-architect from Postman collection ${suite.source}.`);
  out.push("import { test, expect } from '@playwright/test';");
  out.push('');
  out.push('// Collection variables. Override any of them with an environment variable of the same name (upper-cased).');
  out.push('const vars: Record<string, string> = {');
  for (const [k, v] of Object.entries(vars)) out.push(`  ${JSON.stringify(k)}: process.env[${q(k.toUpperCase())}] ?? ${q(v)},`);
  out.push('};');
  out.push("const v = (s: string) => s.replace(/\\{\\{(\\w+)\\}\\}/g, (_, k: string) => vars[k] ?? `{{${k}}}`);");
  out.push('');
  out.push(`test.describe(${q(suite.className ?? 'API')}, () => {`);
  for (const r of suite.requests ?? []) {
    const name = [...r.folder, r.name].join(' / ');
    const body: string[] = [];
    const headers = r.headers.length ? `headers: { ${r.headers.map((h) => `${JSON.stringify(h.key)}: v(${q(h.value)})`).join(', ')} }` : '';
    const isJson = r.headers.some((h) => /content-type/i.test(h.key) && /json/i.test(h.value));
    let data: string[] = [];
    if (r.body !== undefined) {
      if (isJson) { try { data = `data: ${JSON.stringify(JSON.parse(r.body), null, 2)}`.split('\n'); } catch { data = [`data: v(${q(r.body)})`]; } }
      else data = [`data: v(${q(r.body)})`];
    }
    const method = r.method.toLowerCase();
    const fn = ['get', 'post', 'put', 'patch', 'delete', 'head'].includes(method) ? method : 'fetch';
    const optLines: string[] = [];
    if (fn === 'fetch') optLines.push(`method: ${q(r.method)},`);
    if (headers) optLines.push(`${headers},`);
    if (data.length) { data[data.length - 1] += ','; optLines.push(...data); }
    if (optLines.length) {
      body.push(`const res = await request.${fn}(v(${q(r.url)}), {`, ...indent(optLines), '});');
    } else body.push(`const res = await request.${fn}(v(${q(r.url)}));`);
    let n = 0; let total = 1;
    if (r.expectedStatus) { body.push(`expect(res.status()).toBe(${r.expectedStatus});`); total++; }
    else { body.push(`expect(res.ok(), \`unexpected status \${res.status()}\`).toBeTruthy();  // NOTE(sdet-architect): no status assertion in source`); noAssertion.push(name); }
    const leftovers = r.testScript.filter((l) => l.trim() && !IGNORABLE.test(l));
    if (leftovers.length) {
      body.push('// TODO(sdet-architect): port the remaining Postman test script:');
      for (const l of leftovers) body.push(`//   ${l}`);
      n++; total++;
      todos.push({ file: suite.source, line: 0, raw: leftovers.join(' | '), where: name });
    }
    tests.push({ name, status: statusOf(total, n), total, todos: n });
    out.push(`  test(${q(name)}, async ({ request }) => {`);
    out.push(...indent(body, 4));
    out.push('  });', '');
  }
  out.push('});');
  out.push('');
  return { code: out.join('\n'), todos, statuses: tests, flaky: [], tests, noAssertion };
}
