// Cucumber: keep the .feature verbatim, generate playwright-bdd style step definitions. Pure.
import type { Locator, StepDefinition, TestSuite } from '../model.js';
import { q } from '../locators.js';
import { linkStep, uniqueSteps } from '../parsers/cucumber.js';
import { type Plan, fieldOn, stdOf } from './plan.js';
import { emitStep, indent, statusOf, type ConversionStatus } from './steps.js';
import type { GenResult } from './pages.js';

export interface BddResult extends GenResult { scenarios: { name: string; status: ConversionStatus; total: number; todos: number }[]; unmatched: string[] }

export function featureBaseName(suite: TestSuite): string {
  return suite.source.replace(/^.*\//, '').replace(/\.feature$/i, '');
}

export function genStepDefinitions(featureSuite: TestSuite, defSuites: TestSuite[], plan: Plan, baseUrl?: string): BddResult {
  const feature = featureSuite.feature!;
  const defs: StepDefinition[] = defSuites.flatMap((s) => s.stepDefinitions ?? []);
  const todos: GenResult['todos'] = [];
  const flaky: GenResult['flaky'] = [];
  const unmatched: string[] = [];
  const used = new Set<string>();
  const defStatus = new Map<StepDefinition, { total: number; todos: number }>();

  const locFor = (defSource: string) => (l: Locator) => {
    const own = plan.pageForSuite.get(defSource);
    const f = fieldOn(own, l);
    if (f && own) { used.add(own.fixture); return `${own.fixture}.${f}`; }
    for (const p of plan.pages) { const g = fieldOn(p, l); if (g) { used.add(p.fixture); return `${p.fixture}.${g}`; } }
    return stdOf(plan, l).expr;
  };
  const callTarget = (cls: string) => { const p = plan.pageByClass.get(cls); if (!p) return undefined; used.add(p.fixture); return p.fixture; };

  const blocks: string[] = [];
  const emittedDefs = new Set<StepDefinition>();
  for (const gs of uniqueSteps(feature)) {
    const link = linkStep(gs, defs);
    if (!link.def) {
      unmatched.push(`${gs.keyword} ${gs.text}`);
      todos.push({ file: featureSuite.source, line: gs.line, raw: `${gs.keyword} ${gs.text}`, where: 'no step definition found' });
      blocks.push(`${gs.keyword}(${q(gs.text)}, async ({ page }) => {`, `  // TODO(sdet-architect): no step definition found for this step  [${featureSuite.source}:${gs.line}]`, '});', '');
      continue;
    }
    const def = link.def;
    if (emittedDefs.has(def)) continue;
    emittedDefs.add(def);
    const ctx = { page: 'page', loc: locFor(def.source), callTarget, baseUrl, params: new Set(def.params), sourceFile: def.source };
    const body: string[] = [];
    let n = 0;
    for (const s of def.steps) {
      const e = emitStep(s, ctx);
      body.push(...e.code);
      if (e.todo) { n++; todos.push({ file: def.source, line: s.line, raw: s.raw.trim(), where: `${def.keyword} ${def.pattern}` }); }
      if (e.flaky) flaky.push({ file: def.source, line: s.line, raw: s.raw.trim() });
    }
    defStatus.set(def, { total: def.steps.length, todos: n });
    const pattern = /^\^.*\$$/.test(def.regex) && def.regex === def.pattern ? `/${def.pattern.replace(/\//g, '\\/')}/` : q(def.pattern);
    const params = def.params.map((p) => `, ${p}: string`).join('');
    blocks.push(`${def.keyword}(${pattern}, async ({ page__FIXTURES__ }${params}) => {`, ...indent(body.length ? body : ['// (empty in source)']), '});', '');
  }

  const scenarios: BddResult['scenarios'] = [];
  for (const sc of feature.scenarios) {
    const steps = [...feature.background, ...sc.steps];
    let total = 0; let td = 0;
    for (const gs of steps) {
      const link = linkStep(gs, defs);
      if (!link.def) { total++; td++; continue; }
      const st = defStatus.get(link.def) ?? { total: 1, todos: 1 };
      total += Math.max(st.total, 1); td += st.todos;
    }
    scenarios.push({ name: sc.name, status: statusOf(total, td), total, todos: td });
  }

  const fixtures = [...used].sort().map((f) => `, ${f}`).join('');
  const out: string[] = [];
  out.push(`// Generated by sdet-architect from ${featureSuite.source} and ${defSuites.map((d) => d.source).join(', ') || '(no step definitions)'}.`);
  out.push(`// Runs with playwright-bdd: \`npx bddgen && npx playwright test --project=bdd\`.`);
  out.push("import { createBdd } from 'playwright-bdd';");
  out.push(used.size ? "import { test, expect } from '../../src/fixtures';" : "import { test, expect } from '@playwright/test';");
  out.push('');
  out.push('const { Given, When, Then } = createBdd(test);');
  out.push('');
  out.push(blocks.join('\n').replace(/__FIXTURES__/g, fixtures).trimEnd());
  out.push('');
  let code = out.join('\n');
  if (!/\bexpect\(/.test(code)) code = code.replace('import { test, expect } from', 'import { test } from');
  return { code, todos, statuses: scenarios, flaky, scenarios, unmatched };
}
