// Page-object class generator. Pure.
import type { Locator } from '../model.js';
import { type Plan, type PlannedPage, fieldOn, stdOf } from './plan.js';
import { emitStep, indent, methodReturnType, statusOf, type ConversionStatus } from './steps.js';

export interface GenResult { code: string; todos: { file: string; line: number; raw: string; where: string }[]; statuses: { name: string; status: ConversionStatus; total: number; todos: number }[]; flaky: { file: string; line: number; raw: string }[] }

export function genPageClass(page: PlannedPage, plan: Plan, baseUrl?: string): GenResult {
  const todos: GenResult['todos'] = [];
  const flaky: GenResult['flaky'] = [];
  const statuses: GenResult['statuses'] = [];
  const loc = (l: Locator) => { const f = fieldOn(page, l); return f ? `this.${f}` : `this.${stdOf(plan, l).expr}`; };
  const callTarget = (cls: string) => { const p = plan.pageByClass.get(cls); return p ? `new ${p.className}(this.page)` : undefined; };
  const imports = new Set<string>();
  for (const m of page.methods) for (const s of m.steps) if (s.kind === 'call' && s.call && plan.pageByClass.get(s.call.object) && plan.pageByClass.get(s.call.object)!.className !== page.className) imports.add(plan.pageByClass.get(s.call.object)!.className);
  const usesExpect = page.methods.some((m) => m.steps.some((s) => s.kind === 'assert'));

  const out: string[] = [];
  out.push(`// Generated by sdet-architect from ${page.sourceFile}${page.synthetic ? ' (locators used inline in the test class)' : ''}.`);
  out.push(`import { type Page, type Locator${usesExpect ? ', expect' : ''} } from '@playwright/test';`);
  for (const i of imports) { const p = plan.pages.find((x) => x.className === i)!; out.push(`import { ${i} } from './${p.file.replace(/^src\/pages\//, '').replace(/\.ts$/, '')}';`); }
  out.push('');
  out.push(`export class ${page.className} {`);
  for (const f of page.fields) out.push(`  readonly ${f.name}: Locator;${f.std.confidence < 0.6 ? `  // LOW CONFIDENCE (${f.std.confidence.toFixed(2)}): ${f.std.note ?? ''} <- ${f.locator.strategy}: ${f.locator.value}` : ''}`);
  out.push('');
  out.push('  constructor(readonly page: Page) {');
  for (const f of page.fields) out.push(`    this.${f.name} = ${f.std.expr};`);
  out.push('  }');
  for (const m of page.methods) {
    const params = m.params.map((p) => `${p}: string`).join(', ');
    const ctx = { page: 'this.page', loc, callTarget, baseUrl, params: new Set(m.params), sourceFile: page.sourceFile };
    const body: string[] = [];
    let n = 0;
    for (const s of m.steps) {
      const e = emitStep(s, ctx);
      body.push(...e.code);
      if (e.todo) { n++; todos.push({ file: page.sourceFile, line: s.line, raw: s.raw.trim(), where: `${page.className}.${m.name}` }); }
      if (e.flaky) flaky.push({ file: page.sourceFile, line: s.line, raw: s.raw.trim() });
    }
    statuses.push({ name: `${page.className}.${m.name}`, status: statusOf(m.steps.length, n), total: m.steps.length, todos: n });
    out.push('');
    out.push(`  async ${m.name}(${params}): ${methodReturnType(m.steps)} {`);
    out.push(...indent(body.length ? body : [`// (empty in source)`], 4));
    out.push('  }');
  }
  out.push('}');
  out.push('');
  return { code: out.join('\n'), todos, statuses, flaky };
}

export function genFixtures(pages: PlannedPage[]): string {
  const out: string[] = [];
  out.push('// Generated by sdet-architect: one fixture per page object so specs can destructure them.');
  out.push("import { test as base } from '@playwright/test';");
  for (const p of pages) out.push(`import { ${p.className} } from '../pages/${p.file.replace(/^src\/pages\//, '').replace(/\.ts$/, '')}';`);
  out.push('');
  out.push('export type PageFixtures = {');
  for (const p of pages) out.push(`  ${p.fixture}: ${p.className};`);
  out.push('};');
  out.push('');
  out.push('export const test = base.extend<PageFixtures>({');
  for (const p of pages) out.push(`  ${p.fixture}: async ({ page }, use) => { await use(new ${p.className}(page)); },`);
  out.push('});');
  out.push('');
  out.push("export { expect } from '@playwright/test';");
  out.push('');
  return out.join('\n');
}

