// Project scaffolding: package.json, playwright.config.ts, .mcp.json, tsconfig.json, CI workflow. Pure.
import { q } from '../locators.js';

export interface ProjectOpts { orgSlug: string; baseUrl: string; hasBdd: boolean; hasApi: boolean; hasUi: boolean; testIdAttribute?: string }

export function genPackageJson(o: ProjectOpts): string {
  const pkg = {
    name: `${o.orgSlug}-playwright`,
    private: true,
    version: '0.1.0',
    description: `Standardised Playwright + Playwright MCP test architecture for ${o.orgSlug} (generated by sdet-architect).`,
    type: 'module',
    scripts: {
      test: o.hasBdd ? 'npx bddgen && playwright test' : 'playwright test',
      'test:ui': 'playwright test --ui',
      'test:headed': 'playwright test --headed',
      ...(o.hasApi ? { 'test:api': 'playwright test --project=api' } : {}),
      ...(o.hasBdd ? { 'test:bdd': 'npx bddgen && playwright test --project=bdd' } : {}),
      report: 'playwright show-report',
      mcp: 'mcp-server-playwright --config playwright-mcp.config.json',
      typecheck: 'tsc --noEmit',
    },
    devDependencies: {
      '@playwright/test': '^1.55.0',
      '@playwright/mcp': '^0.0.40',
      '@types/node': '^24.0.0',
      typescript: '^5.8.3',
      ...(o.hasBdd ? { 'playwright-bdd': '^8.0.0' } : {}),
    },
  };
  return JSON.stringify(pkg, null, 2) + '\n';
}

export function genPlaywrightConfig(o: ProjectOpts): string {
  const lines: string[] = [];
  lines.push('// Generated by sdet-architect. Single source of truth for every project (UI, API, BDD).');
  lines.push("import { defineConfig, devices } from '@playwright/test';");
  if (o.hasBdd) {
    lines.push("import { defineBddConfig } from 'playwright-bdd';");
    lines.push('');
    lines.push('const bddTestDir = defineBddConfig({');
    lines.push("  features: 'tests/features/**/*.feature',");
    lines.push("  steps: ['tests/steps/**/*.ts', 'src/fixtures/index.ts'],");
    lines.push('});');
  }
  lines.push('');
  lines.push('export default defineConfig({');
  lines.push("  testDir: './tests',");
  lines.push('  fullyParallel: true,');
  lines.push('  forbidOnly: !!process.env.CI,');
  lines.push('  retries: process.env.CI ? 2 : 0,');
  lines.push('  workers: process.env.CI ? 2 : undefined,');
  lines.push("  reporter: [['list'], ['html', { open: 'never' }], ['json', { outputFile: 'test-results/results.json' }]],");
  lines.push('  use: {');
  lines.push(`    baseURL: process.env.BASE_URL ?? ${q(o.baseUrl)},`);
  if (o.testIdAttribute && o.testIdAttribute !== 'data-testid') lines.push(`    testIdAttribute: ${q(o.testIdAttribute)},`);
  lines.push("    trace: 'on-first-retry',");
  lines.push("    video: 'on-first-retry',");
  lines.push("    screenshot: 'only-on-failure',");
  lines.push('  },');
  lines.push('  projects: [');
  if (o.hasUi) {
    lines.push("    { name: 'chromium', testIgnore: ['**/api/**', '**/features/**', '**/steps/**'], use: { ...devices['Desktop Chrome'] } },");
    lines.push("    { name: 'firefox', testIgnore: ['**/api/**', '**/features/**', '**/steps/**'], use: { ...devices['Desktop Firefox'] } },");
  }
  if (o.hasApi) lines.push("    { name: 'api', testMatch: /tests\\/api\\/.*\\.spec\\.ts/ },");
  if (o.hasBdd) lines.push("    { name: 'bdd', testDir: bddTestDir, use: { ...devices['Desktop Chrome'] } },");
  lines.push('  ],');
  lines.push('});');
  lines.push('');
  return lines.join('\n');
}

export function genMcpJson(): string {
  return JSON.stringify({
    mcpServers: {
      playwright: {
        command: 'npx',
        args: ['@playwright/mcp@latest', '--config', 'playwright-mcp.config.json'],
      },
    },
  }, null, 2) + '\n';
}

export function genMcpServerConfig(o: ProjectOpts): string {
  return JSON.stringify({
    browser: { browserName: 'chromium', launchOptions: { headless: true } },
    capabilities: ['core', 'tabs', 'pdf', 'history', 'wait', 'files'],
    outputDir: './test-results/mcp',
    _comment: `Navigate to ${o.baseUrl}; the MCP client can drive the same pages the specs cover.`,
  }, null, 2) + '\n';
}

export function genTsconfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler', strict: true, esModuleInterop: true,
      skipLibCheck: true, noEmit: true, types: ['node'],
    },
    include: ['playwright.config.ts', 'src/**/*.ts', 'tests/**/*.ts'],
  }, null, 2) + '\n';
}

export function genWorkflow(o: ProjectOpts): string {
  return `name: playwright
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm test
        env:
          BASE_URL: \${{ vars.BASE_URL || '${o.baseUrl}' }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
`;
}

export function genGitignore(): string { return 'node_modules/\ntest-results/\nplaywright-report/\n.features-gen/\n'; }
