// tests/<name>.spec.ts generator for UI suites and markdown test plans. Pure.
import type { Locator, TestSuite } from '../model.js';
import { q } from '../locators.js';
import { type Plan, fieldOn, stdOf } from './plan.js';
import { emitStep, indent, statusOf, type ConversionStatus } from './steps.js';
import type { GenResult } from './pages.js';

export interface SpecResult extends GenResult { tests: { name: string; status: ConversionStatus; total: number; todos: number }[]; noAssertion: string[] }

export function specFileName(suite: TestSuite): string {
  const base = suite.source.replace(/^.*\//, '').replace(/\.(java|py|cs|js|ts|mjs|cjs|md|json)$/i, '').replace(/\.(test|spec)$/i, '');
  return `tests/${base}.spec.ts`;
}

export function genSpec(suite: TestSuite, plan: Plan, baseUrl?: string, hints?: Map<import('../model.js').Step, string>): SpecResult {
  const own = plan.pageForSuite.get(suite.source);
  const todos: GenResult['todos'] = [];
  const flaky: GenResult['flaky'] = [];
  const tests: SpecResult['tests'] = [];
  const noAssertion: string[] = [];
  const used = new Set<string>();
  const loc = (l: Locator) => {
    const f = fieldOn(own, l);
    if (f && own) { used.add(own.fixture); return `${own.fixture}.${f}`; }
    // locator belongs to a page-object class that was referenced by alias
    for (const p of plan.pages) { const g = fieldOn(p, l); if (g) { used.add(p.fixture); return `${p.fixture}.${g}`; } }
    return stdOf(plan, l).expr;
  };
  const callTarget = (cls: string) => { const p = plan.pageByClass.get(cls); if (!p) return undefined; used.add(p.fixture); return p.fixture; };
  const ctx = { page: 'page', loc, callTarget, baseUrl, params: new Set<string>(), hints, sourceFile: suite.source };

  const emitBody = (steps: TestSuite['tests'][number]['steps'], where: string) => {
    const body: string[] = [];
    let n = 0;
    for (const s of steps) {
      const e = emitStep(s, ctx);
      body.push(...e.code);
      if (e.todo) { n++; todos.push({ file: suite.source, line: s.line, raw: s.raw.trim(), where }); }
      if (e.flaky) flaky.push({ file: suite.source, line: s.line, raw: s.raw.trim() });
    }
    return { body, n };
  };

  const blocks: string[] = [];
  const hookName: Record<string, string> = { beforeEach: 'test.beforeEach', afterEach: 'test.afterEach', beforeAll: 'test.beforeAll', afterAll: 'test.afterAll' };
  for (const h of suite.hooks) {
    if (!h.steps.length) continue;
    const { body } = emitBody(h.steps, h.name);
    const fx = h.kind.endsWith('All') ? '{ browser }' : '{ page__FX__ }';
    if (h.kind.endsWith('All')) {
      blocks.push(`  // NOTE(sdet-architect): ${h.kind} hooks have no per-test page; review whether this belongs in beforeEach.`);
      blocks.push(`  ${hookName[h.kind]}(async (${fx}) => {`, ...indent(body.map((l) => `// ${l}`), 4), '  });', '');
      continue;
    }
    blocks.push(`  ${hookName[h.kind]}(async (${fx}) => {`, ...indent(body, 4), '  });', '');
  }
  for (const t of suite.tests) {
    const { body, n } = emitBody(t.steps, t.name);
    const status = statusOf(t.steps.length, n);
    tests.push({ name: t.name, status, total: t.steps.length, todos: n });
    if (!t.steps.some((s) => s.kind === 'assert') && suite.kind !== 'test-plan') noAssertion.push(t.name);
    const fixme = status === 'manual' ? `    test.fixme(true, 'sdet-architect: ${n}/${t.steps.length} steps need manual conversion');` : '';
    const skip = t.tags?.includes('skip') ? `    test.skip(true, 'skipped in source');` : '';
    blocks.push(`  test(${q(t.name)}, async ({ page__FX__ }) => {`);
    if (fixme) blocks.push(fixme);
    if (skip) blocks.push(skip);
    blocks.push(...indent(body.length ? body : ['// (no steps found in source)'], 4));
    blocks.push('  });', '');
  }
  // fixture names are only known after emitting bodies, so fill the parameter lists last
  const fixtures = [...used].sort().map((f) => `, ${f}`).join('');
  const rendered = blocks.join('\n').replace(/__FX__/g, fixtures);

  const out: string[] = [];
  out.push(`// Generated by sdet-architect from ${suite.source} (${suite.kind}).`);
  out.push(used.size ? `import { test, expect } from '../src/fixtures';` : `import { test, expect } from '@playwright/test';`);
  out.push('');
  out.push(`test.describe(${q(suite.className ?? suite.source)}, () => {`);
  out.push(rendered.trimEnd());
  out.push('});');
  out.push('');
  return { code: ensureExpectUsed(out.join('\n')), todos, statuses: tests.map((t) => ({ ...t })), flaky, tests, noAssertion };
}

/** Avoid "expect is declared but never used" style lint noise: drop it from the import when unused. */
function ensureExpectUsed(code: string): string {
  const usesExpect = /\bexpect\(/.test(code);
  return usesExpect ? code : code.replace("import { test, expect } from", 'import { test } from');
}

/** Markdown test plans become fixme'd scaffolds so the TODO list is visible in the runner. */
export function parseTestPlan(md: string, file: string): TestSuite {
  const suite: TestSuite = { source: file, language: 'markdown', kind: 'test-plan', tests: [], pageObjects: [], hooks: [], locators: [], urls: [], constants: {} };
  const lines = md.split('\n');
  let current: TestSuite['tests'][number] | undefined;
  for (let i = 0; i < lines.length; i++) {
    const t = lines[i].trim();
    let m: RegExpExecArray | null;
    if ((m = /^#{1,6}\s+(.*)$/.exec(t))) {
      if (i === 0 || /^#\s/.test(t)) { suite.className ??= m[1].trim(); if (/^#\s/.test(t)) continue; }
      current = { name: m[1].trim(), line: i + 1, steps: [] };
      suite.tests.push(current);
    } else if (current && (m = /^(?:\d+[.)]|[-*]|\[ \])\s+(.*)$/.exec(t))) {
      current.steps.push({ kind: 'unknown', raw: m[1].trim(), line: i + 1 });
      const u = /https?:\/\/[^\s)]+/.exec(m[1]); if (u) suite.urls.push(u[0]);
    }
  }
  return suite;
}
