// Pure code generation for the provisioned Playwright + Playwright MCP project.
// Every function returns strings; `generateInfra` returns the full file list.
import { toPascalCase, uniqueNames } from './locators.js';
import type { PageRecord } from './types.js';

export interface GeneratedFile { relPath: string; content: string; kind: string }

export interface InfraOptions {
  targetUrl: string;
  orgSlug: string;
  mcp: boolean;
  generatedAt?: string;
}

function q(s: string): string { return JSON.stringify(s); }

/** `/` -> HomePage, `/about-us` -> AboutUsPage, `/blog/post-1?x=1` -> BlogPost1Page */
export function pageClassName(pathname: string): string {
  const clean = pathname.split('?')[0]!.split('#')[0]!;
  const pascal = toPascalCase(clean.replace(/\.[a-z0-9]+$/i, ''));
  const base = pascal || 'Home';
  return (/^[0-9]/.test(base) ? 'Page' + base : base) + 'Page';
}

export function pageFileName(className: string): string {
  return `${className}.page.ts`;
}

/** Assign unique class names to a crawled page set (stable order). */
export function assignClassNames(pages: PageRecord[]): Map<PageRecord, string> {
  const names = uniqueNames(pages.map(p => pageClassName(p.path)));
  return new Map(pages.map((p, i) => [p, names[i]!]));
}

export function generatePackageJson(opts: InfraOptions): string {
  const scripts: Record<string, string> = {
    test: 'playwright test',
    'test:ui': 'playwright test --ui',
    'test:headed': 'playwright test --headed --project=chromium',
    report: 'playwright show-report',
    ...(opts.mcp ? { mcp: 'npx @playwright/mcp@latest --headless' } : {}),
  };
  return JSON.stringify({
    name: `${opts.orgSlug}-e2e`,
    version: '0.1.0',
    private: true,
    type: 'module',
    description: `Playwright test infrastructure for ${opts.targetUrl}, provisioned by The Forward Deployed Tester.`,
    scripts,
    devDependencies: {
      '@playwright/test': '^1.55.0',
      ...(opts.mcp ? { '@playwright/mcp': '^0.0.40' } : {}),
      '@types/node': '^24.0.0',
      typescript: '^5.8.3',
    },
  }, null, 2) + '\n';
}

export function generatePlaywrightConfig(opts: InfraOptions): string {
  return `import { defineConfig, devices } from '@playwright/test';

/**
 * Generated by The Forward Deployed Tester for ${opts.targetUrl}.
 * Override the base URL per environment with BASE_URL=https://staging.example.test npm test
 */
export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : undefined,
  reporter: [['html', { open: 'never' }], ['list']],
  timeout: 30_000,
  expect: { timeout: 5_000 },
  use: {
    baseURL: process.env.BASE_URL ?? ${q(opts.targetUrl)},
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
    { name: 'firefox', use: { ...devices['Desktop Firefox'] } },
    { name: 'webkit', use: { ...devices['Desktop Safari'] } },
    { name: 'mobile-chrome', use: { ...devices['Pixel 7'] } },
    { name: 'mobile-safari', use: { ...devices['iPhone 14'] } },
  ],
});
`;
}

export function generateMcpJson(opts: InfraOptions): string {
  return JSON.stringify({
    mcpServers: {
      playwright: {
        command: 'npx',
        args: ['@playwright/mcp@latest', '--headless', '--browser', 'chromium'],
        env: { BASE_URL: opts.targetUrl },
      },
    },
  }, null, 2) + '\n';
}

export function generateFixtures(): string {
  return `import { test as base, expect } from '@playwright/test';

/**
 * Collects console errors and uncaught page errors for the lifetime of a test.
 * Assert on it with: expect(consoleErrors).toEqual([])
 */
export const test = base.extend<{ consoleErrors: string[] }>({
  consoleErrors: async ({ page }, use) => {
    const errors: string[] = [];
    page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()); });
    page.on('pageerror', (err) => errors.push(\`pageerror: \${err.message}\`));
    await use(errors);
  },
});

export { expect };
`;
}

function specTitle(p: PageRecord): string {
  const t = (p.title || p.h1Text || p.path).replace(/\s+/g, ' ').trim().slice(0, 60);
  return `${p.path} renders (${t})`;
}

export function generateSmokeSpec(pages: PageRecord[]): string {
  const classNames = assignClassNames(pages);
  const imports = pages.map(p => {
    const cls = classNames.get(p)!;
    return `import { ${cls} } from '../pages/${cls}.page';`;
  }).join('\n');

  const tests = pages.map(p => {
    const cls = classNames.get(p)!;
    const lines: string[] = [];
    lines.push(`  test(${q(specTitle(p))}, async ({ page, consoleErrors }) => {`);
    lines.push(`    const po = new ${cls}(page);`);
    lines.push(`    const response = await po.goto();`);
    lines.push(`    expect(response?.status() ?? 200, 'page should respond successfully').toBeLessThan(400);`);
    if (p.title) lines.push(`    await expect(page).toHaveTitle(${q(p.title)});`);
    if (p.hasH1 && p.h1Text) lines.push(`    await expect(page.getByRole('heading', { level: 1 }).first()).toContainText(${q(p.h1Text.slice(0, 60))});`);
    else if (p.hasH1) lines.push(`    await expect(page.getByRole('heading', { level: 1 }).first()).toBeVisible();`);
    else lines.push(`    // NOTE: recon found no <h1> on this page (see findings). Add one, then assert on it here.`);
    lines.push(`    expect(consoleErrors, 'no console errors during load').toEqual([]);`);
    lines.push(`  });`);
    return lines.join('\n');
  }).join('\n\n');

  return `import { test, expect } from './fixtures';
${imports}

/**
 * Smoke suite generated by The Forward Deployed Tester: one test per page found during
 * reconnaissance. Each test navigates, checks the response, title/h1 and that the console stayed clean.
 */
test.describe('smoke', () => {
${tests}
});
`;
}

export function generatePageObject(p: PageRecord, className = pageClassName(p.path)): string {
  const props = p.elements.map(el => {
    const d = el.descriptor;
    const desc = [d.tag, d.type ? `type=${d.type}` : '', el.locator.role ?? '', `(${el.locator.strategy}, ${el.locator.confidence} confidence)`]
      .filter(Boolean).join(' ');
    return `  /** ${desc} */\n  get ${el.property}(): Locator { return this.${el.locator.code}; }`;
  }).join('\n\n');

  return `import type { Page, Locator, Response } from '@playwright/test';

/**
 * Page object for ${p.url}
 * Title: ${(p.title || '(untitled)').replace(/\*\//g, '* /')}
 * Generated by The Forward Deployed Tester from the accessibility tree. Review low-confidence locators.
 */
export class ${className} {
  readonly path = ${q(p.path)};

  constructor(readonly page: Page) {}

  async goto(): Promise<Response | null> {
    return this.page.goto(this.path);
  }
${props ? '\n' + props + '\n' : ''}}
`;
}

export function generateWorkflow(): string {
  return `name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
  schedule:
    - cron: '0 6 * * 1-5'
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          BASE_URL: \${{ vars.BASE_URL }}
      - uses: actions/upload-artifact@v4
        if: \${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
`;
}

export function generateReadme(pages: PageRecord[], opts: InfraOptions): string {
  const classNames = assignClassNames(pages);
  const pageRows = pages.map(p => `| \`${p.path}\` | \`pages/${classNames.get(p)}.page.ts\` | ${p.elements.length} |`).join('\n');
  const mcpSection = opts.mcp ? `
## Driving the browser from an MCP client

\`.mcp.json\` registers the Playwright MCP server. Any MCP-capable client (Claude Code, Cursor, a custom agent)
that reads this file can open \`${opts.targetUrl}\`, click through flows and generate new specs.

\`\`\`bash
npm run mcp            # start the server standalone (stdio), or let your client launch it from .mcp.json
\`\`\`

Suggested prompts once connected:

- "Open the base URL, navigate to every page in \`pages/\`, and report any element whose locator no longer resolves."
- "Exercise the form on \`/contact\` with valid and invalid data and write a spec in \`tests/contact.spec.ts\` using the page object."
- "Take a snapshot of the home page and propose three regression tests."
` : '';

  return `# ${opts.orgSlug} end-to-end tests

Provisioned${opts.generatedAt ? ` on ${opts.generatedAt}` : ''} by **The Forward Deployed Tester** against \`${opts.targetUrl}\`.

## Quick start

\`\`\`bash
npm install
npx playwright install --with-deps
npm test               # headless, all projects
npm run test:ui        # Playwright UI mode
npm run report         # open the last HTML report
BASE_URL=https://staging.example.test npm test   # point at another environment
\`\`\`

## Layout

- \`playwright.config.ts\` — baseURL, trace-on-retry, HTML reporter, desktop (chromium/firefox/webkit) + mobile projects
- \`tests/fixtures.ts\` — a \`consoleErrors\` fixture that collects console + page errors per test
- \`tests/smoke.spec.ts\` — one smoke test per crawled page
- \`pages/*.page.ts\` — page objects with locators derived from the accessibility tree
- \`.github/workflows/playwright.yml\` — CI on push, PR, nightly and manual dispatch
${opts.mcp ? '- `.mcp.json` — Playwright MCP server configuration\n' : ''}
## Pages covered

| Path | Page object | Locators |
| --- | --- | --- |
${pageRows || '| (none) | | |'}
${mcpSection}
## Extending

1. Add a spec under \`tests/\` and import \`test\`/\`expect\` from \`./fixtures\`.
2. Reach elements through the page objects; prefer \`getByRole\` / \`getByLabel\` over CSS.
3. Locators marked *low confidence* in the page objects fell back to CSS — add \`data-testid\` attributes or accessible names in the app and regenerate.
`;
}

export function generateInfra(pages: PageRecord[], opts: InfraOptions): GeneratedFile[] {
  const classNames = assignClassNames(pages);
  const files: GeneratedFile[] = [
    { relPath: 'package.json', content: generatePackageJson(opts), kind: 'infra/package' },
    { relPath: 'playwright.config.ts', content: generatePlaywrightConfig(opts), kind: 'infra/config' },
    { relPath: 'tests/fixtures.ts', content: generateFixtures(), kind: 'infra/fixture' },
    { relPath: 'tests/smoke.spec.ts', content: generateSmokeSpec(pages), kind: 'infra/spec' },
    { relPath: 'README.md', content: generateReadme(pages, opts), kind: 'infra/readme' },
    { relPath: '.github/workflows/playwright.yml', content: generateWorkflow(), kind: 'infra/ci' },
    { relPath: '.gitignore', content: 'node_modules/\ntest-results/\nplaywright-report/\nblob-report/\nplaywright/.cache/\n', kind: 'infra/misc' },
  ];
  if (opts.mcp) files.push({ relPath: '.mcp.json', content: generateMcpJson(opts), kind: 'infra/mcp' });
  for (const p of pages) {
    const cls = classNames.get(p)!;
    files.push({ relPath: `pages/${pageFileName(cls)}`, content: generatePageObject(p, cls), kind: 'infra/page-object' });
  }
  return files;
}
