// MIGRATION.md builder. Pure function on a report model.
import type { FileKind } from './model.js';
import type { InventoryEntry } from './inventory.js';
import type { ConversionStatus } from './generators/steps.js';

export interface FileStatus { source: string; kind: FileKind; output: string; status: ConversionStatus | 'kept' | 'n/a'; tests: number; converted: number; partial: number; manual: number }
export interface TodoItem { file: string; line: number; raw: string; where: string }
export interface ReportModel {
  orgSlug: string;
  sourceDir: string;
  outputDir: string;
  baseUrl: string;
  dryRun: boolean;
  inventory: InventoryEntry[];
  counts: Record<FileKind, number>;
  files: FileStatus[];
  totals: { tests: number; converted: number; partial: number; manual: number; steps: number; stepsConverted: number; coveragePct: number };
  todos: TodoItem[];
  locators: { total: number; low: number; histogram: Record<string, number>; byStrategy: Record<string, number>; lowList: { file: string; line: number; strategy: string; value: string; expr: string; confidence: number; note?: string }[] };
  findings: { flaky: number; duplication: number; quality: number; conversion: number; locator: number };
  generatedFiles: string[];
  llmUsed: boolean;
}

const KIND_ORDER: FileKind[] = ['selenium-java', 'selenium-python', 'selenium-csharp', 'selenium-js', 'cypress', 'cucumber-feature', 'step-definitions', 'page-object', 'postman-collection', 'test-plan', 'config', 'unknown'];

export function buildMigrationReport(m: ReportModel): string {
  const L: string[] = [];
  const pct = (a: number, b: number) => (b ? `${((a / b) * 100).toFixed(1)}%` : 'n/a');
  L.push(`# Migration report: ${m.orgSlug} -> Playwright + Playwright MCP`);
  L.push('');
  L.push(`Generated by **sdet-architect** (plate 45)${m.dryRun ? ' — DRY RUN, nothing was written' : ''}.`);
  L.push('');
  L.push(`- Source estate: \`${m.sourceDir}\``);
  L.push(`- Output: \`${m.outputDir}\``);
  L.push(`- Base URL: \`${m.baseUrl}\``);
  L.push(`- Files scanned: ${m.inventory.length}`);
  L.push(`- Tests found: ${m.totals.tests} — converted ${m.totals.converted}, partial ${m.totals.partial}, manual ${m.totals.manual}`);
  L.push(`- **Conversion coverage: ${m.totals.coveragePct.toFixed(1)}%** (${m.totals.stepsConverted}/${m.totals.steps} steps emitted as Playwright code, the rest are TODOs)`);
  L.push(`- Locators: ${m.locators.total} unique, ${m.locators.low} below the 0.60 confidence threshold`);
  L.push(`- Model assistance: ${m.llmUsed ? 'used for leftovers (suggestions only, as comments)' : 'none (LLM_PROVIDER=none) — output is fully deterministic'}`);
  L.push('');
  L.push('## 1. Inventory');
  L.push('');
  L.push('| Kind | Files |');
  L.push('|---|---:|');
  for (const k of KIND_ORDER) if (m.counts[k]) L.push(`| ${k} | ${m.counts[k]} |`);
  L.push('');
  L.push('| File | Kind | Language | Lines |');
  L.push('|---|---|---|---:|');
  for (const e of m.inventory) L.push(`| \`${e.path}\` | ${e.kind} | ${e.language} | ${e.lines} |`);
  L.push('');
  L.push('## 2. Per-file conversion status');
  L.push('');
  L.push('| Source | Kind | Generated | Status | Tests | Converted | Partial | Manual |');
  L.push('|---|---|---|---|---:|---:|---:|---:|');
  for (const f of m.files) L.push(`| \`${f.source}\` | ${f.kind} | \`${f.output}\` | ${f.status} | ${f.tests} | ${f.converted} | ${f.partial} | ${f.manual} |`);
  L.push('');
  L.push('Status meaning: **converted** = every step emitted as Playwright code; **partial** = some `TODO(sdet-architect)` lines remain; **manual** = half or more of the steps are TODOs (the test is generated with `test.fixme`).');
  L.push('');
  L.push(`## 3. TODO list (${m.todos.length})`);
  L.push('');
  if (!m.todos.length) L.push('Nothing left to convert by hand.');
  else {
    L.push('Every line below is also present in the generated code as `// TODO(sdet-architect): ...` so it shows up in the editor and in `grep`.');
    L.push('');
    L.push('| # | Source | Where | Original line |');
    L.push('|---:|---|---|---|');
    m.todos.forEach((t, i) => L.push(`| ${i + 1} | \`${t.file}:${t.line || '-'}\` | ${t.where} | \`${t.raw.replace(/\|/g, '\\|').slice(0, 160)}\` |`));
  }
  L.push('');
  L.push('## 4. Locator confidence');
  L.push('');
  L.push('| Confidence | Locators |');
  L.push('|---|---:|');
  for (const [bucket, n] of Object.entries(m.locators.histogram)) L.push(`| ${bucket} | ${n} |`);
  L.push('');
  L.push('| Source strategy | Count |');
  L.push('|---|---:|');
  for (const [s, n] of Object.entries(m.locators.byStrategy).sort((a, b) => b[1] - a[1])) L.push(`| ${s} | ${n} |`);
  L.push('');
  if (m.locators.lowList.length) {
    L.push('Low-confidence locators to review (also recorded as `locator` findings):');
    L.push('');
    L.push('| Source | Strategy | Value | Generated | Confidence | Why |');
    L.push('|---|---|---|---|---:|---|');
    for (const l of m.locators.lowList) L.push(`| \`${l.file}:${l.line}\` | ${l.strategy} | \`${l.value.replace(/\|/g, '\\|')}\` | \`${l.expr.replace(/\|/g, '\\|')}\` | ${l.confidence.toFixed(2)} | ${l.note ?? ''} |`);
    L.push('');
  }
  L.push('## 5. Findings summary');
  L.push('');
  L.push(`- conversion: ${m.findings.conversion} unconvertible constructs`);
  L.push(`- flakiness: ${m.findings.flaky} hard waits removed (Playwright auto-waits; re-add \`waitForTimeout\` only with a written reason)`);
  L.push(`- duplication: ${m.findings.duplication} locators repeated across files (now single fields in page objects)`);
  L.push(`- quality: ${m.findings.quality} tests without any assertion`);
  L.push(`- locator: ${m.findings.locator} low-confidence locators`);
  L.push('');
  L.push('## 6. Generated architecture');
  L.push('');
  L.push('```');
  for (const f of m.generatedFiles) L.push(f);
  L.push('```');
  L.push('');
  L.push('## 7. Recommended next steps');
  L.push('');
  L.push('1. `cd` into the output, `npm install`, `npx playwright install --with-deps`.');
  L.push('2. Set `BASE_URL` (or accept the detected default) and run `npm test -- --project=chromium` on one spec at a time.');
  L.push('3. Work the TODO list top-down; each TODO carries its source `file:line`. Prefer `getByRole`/`getByLabel`/`getByTestId` when you touch a locator.');
  L.push('4. Review every LOW CONFIDENCE field in `src/pages/*.page.ts`; ask the product team to add `data-testid` where the DOM offers nothing stable.');
  L.push('5. Delete the removed hard waits for good once the specs are green three runs in a row; they are flagged with `NOTE(sdet-architect)`.');
  L.push('6. Add the tests without assertions to the quality backlog: a passing test that asserts nothing proves nothing.');
  L.push('7. Wire `.github/workflows/playwright.yml` into the pipeline; the HTML report is uploaded as an artifact on every run.');
  L.push('');
  L.push('## 8. How to run from an MCP client');
  L.push('');
  L.push('The generated project ships a `.mcp.json` that registers the Playwright MCP server. Any MCP-capable client (Claude Code, Cursor, an agent SDK) can:');
  L.push('');
  L.push('```');
  L.push('# in the generated project');
  L.push('npm install');
  L.push('npm run mcp            # starts @playwright/mcp with playwright-mcp.config.json');
  L.push('```');
  L.push('');
  L.push('Then, from the client: open the project (it picks up `.mcp.json`), ask the agent to `browser_navigate` to the base URL, and use the page objects in `src/pages/` as the vocabulary for exploratory checks — the same locators the specs use. To run the suite itself from the client, execute `npx playwright test --reporter=json` and read `test-results/results.json`.');
  L.push('');
  return L.join('\n');
}
